version: "3.8"

services:

  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
# Alternatives to env_file
#   environment:
#     MONGO_INITDB_ROOT_USERNAME:max
#     MONGO_INITDB_ROOT_PASSWORD:secret
#     - MONGO_INITDB_ROOT_USERNAME=max
#     - MONGO_INITDB_ROOT_PASSWORD=secret
    env_file:
      - ./env/mongo.env
#   networks:
#     - goals-net

  backend:
# Shorter form for default Dockerfile
#   build: ./backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
# Force a name on a container
#   container_name: frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000
# Both commands stands for "-it"
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs: