version: "3.8"

services:
  server:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # "read-only" prevents the files to be changed at any moment
  
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated # "delegated" improves performance in the reflection of changes in the container and vice-versa
    # Only necessary when application needs to be accessed from outside the docker network (localhost)
    #ports:
    #  - "3000:9000"
  
  mysql:
    image: "mysql:5.7"
    env_file:
      - ./env/mysql.env
  
  #composer:
  #artisan:
  #npm: