version: "3.8"

services: 
  server:
    #image: 'nginx:stable-alpine'
    build:
      # Setting right context for the dockerfile references
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports: 
      - '8000:80'
    volumes: 
      - ./src:/var/www/html
      # "read-only" prevents the files to be changed at any moment
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    #volumes: 
    #  - ./src:/var/www/html:delegated # "delegated" improves performance in the reflection of changes in the container and vice-versa
    # Only necessary when application needs to be accessed from outside the docker network (localhost)
    #ports:
    #  - "3000:9000"
  mysql:
    image: mysql:5.7
    env_file: 
      - ./env/mysql.env
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes: 
      - ./src:/var/www/html

  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]

  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html