apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: survey-api-dev
  template:
    metadata:
      labels:
        app: survey-api-dev
    spec:
      containers:
      - name: survey-api
        image: maurigvs/survey-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080