apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
  labels:
    group: example
spec:
  replicas: 1
  selector:
    #matchLabels:
    #  app: second-app
    #  tier: backend
    matchExpressions:
      - {key: app, operator: In, values: [second-app, first-app]}
  template:
    metadata:
      labels:
        app: second-app
        tier: backend
    spec:
      containers:
      - name: second-node
        image: maurigvs/kub-first-app:2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"